### Learning Numpy

In [189]:
#Loading numpy package
from numpy  import *

#### Creating a 3 x 5 array

In [190]:
a = arange(15).reshape(3, 5)  #using arange(), NOT arrange()
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### Checking array properties

In [191]:
print("the dimensions of the array are (row, columns): " + str(a.shape))

print("the number of dimensions of the array are: " + str(a.ndim))

print("the type of elements in the array are: " + str(a.dtype))

print("the total number of elements in the array are: " + str(a.size))

print("the type of object \'a\' is: " + str(type(a)))

the dimensions of the array are (row, columns): (3L, 5L)
the number of dimensions of the array are: 2
the type of elements in the array are: int32
the total number of elements in the array are: 15
the type of object 'a' is: <type 'numpy.ndarray'>


#### Ways to create an array

In [192]:
# Correct way to initialize an array. Should contain the elements in []

a = array([1, 2, 3, 4])

# From a regular python list/tuple using array function
# Type of the resulting array is deduced from type of elements in the sequence

a = array([2, 3, 4])
b = array([1.2, 3.5, 4.6])

print("array \'a\' = " + str(a) + "        array \'b\' = " + str(b))
print("\nNOTICE DIFFERENCE BETWEEN TYPES BECAUSE OF ELEMENTS \n")
print("the type of the array \'a\', based on type of array elements is: " + str(a.dtype))
print("the type of the array \'b\', based on type of array elements is:" + str(b.dtype))

# The number of sequences in the array initialization determine how many dimensions it will have

c = array([[1, 2, 3, 4], [1.5, 6.2, 3]])

print("\narray \'c\' = " + str(c) + " is a 2-D array because it contains two sequences")

# The type of array can also be specified during creation with dtype option in the array initialization

d = array([[1,2], [3.5, 4.2]], dtype = complex)

print("\narray \'d\' = " + str(d) + "\nis a complex 2-D array. the type was defined in the creation code: (d = array([], dtype = complex))")

# CREATING ARRAY WITH PLACEHOLDER VALUES
# If we know the size of the array but don't know what the elements are, we can use zeros((row, columns)), ones((row, columns))
# empty((row, columns)) to create arrays with placeholder elements

# Using 'arange' to return an array from a sequence of numbers. It works like an A.P. 
# arange(start_value, end_value, increment)

e = arange(10, 15, 1)

print("\narray \'e\' = " + str(e) + " created using \'arange\'")

array 'a' = [2 3 4]        array 'b' = [ 1.2  3.5  4.6]

NOTICE DIFFERENCE BETWEEN TYPES BECAUSE OF ELEMENTS 

the type of the array 'a', based on type of array elements is: int32
the type of the array 'b', based on type of array elements is:float64

array 'c' = [[1, 2, 3, 4] [1.5, 6.2, 3]] is a 2-D array because it contains two sequences

array 'd' = [[ 1.0+0.j  2.0+0.j]
 [ 3.5+0.j  4.2+0.j]]
is a complex 2-D array. the type was defined in the creation code: (d = array([], dtype = complex))

array 'e' = [10 11 12 13 14] created using 'arange'


#### Basic Operations on Arrays

In [193]:
# Arithmetic operations work on arrays ELEMENTWISE

a = array([20, 30, 40, 50])
b = arange(4)  # this will give the array [0, 1, 2, 3]

c = a - b  # index-wise operations on elements are done
print("the new array c = a - b is: " + str(c))

d = b ** 2  # each element of array 'b' is raised to the power 2
print("\nthe new array d = b**2 is: " + str(d))

print("\nOPERATORS LIKE += and *= TO MODIFY EXISITNG ARRAY\n")

e = ones((2, 3), dtype = int)
print("e (before) " + str(e))
e *= 3
print("\ne (after *=) " + str(e) + "\n")

f = random.random((2, 3))   # random.random((n, m)) will always create a n x m array where each element lies b/w 0 to 1
print("f (before) " + str(f))
f += e
print("\nf (after +=) " + str(f))

the new array c = a - b is: [20 29 38 47]

the new array d = b**2 is: [0 1 4 9]

OPERATORS LIKE += and *= TO MODIFY EXISITNG ARRAY

e (before) [[1 1 1]
 [1 1 1]]

e (after *=) [[3 3 3]
 [3 3 3]]

f (before) [[ 0.52423069  0.50966387  0.7689914 ]
 [ 0.92289205  0.9187579   0.66045064]]

f (after +=) [[ 3.52423069  3.50966387  3.7689914 ]
 [ 3.92289205  3.9187579   3.66045064]]


In [194]:
print("UNARY OPERATIONS on elements of array like: SUM, MAX \n")

a = random.random((2, 3))

print("array \'a\' is: " + str(a) + "\n")

print("sum of elements of the array is: " + str(a.sum()))

print ("the largest element in the array is: " +  str(a.max()))

# By default the operation is done on each element of the array. To apply the operation along a specific 'axis' by specifying
# it in the option of the operation
# For a 2-D array, axis = 0 means columns, axis = 1 means rows

print("\ncolumn-wise sum of elements of the array are: " + str(a.sum(axis = 0)))

print("row-wise largest element of the array are: " + str(a.max(axis = 1)))

UNARY OPERATIONS on elements of array like: SUM, MAX 

array 'a' is: [[ 0.97900827  0.30729789  0.70342391]
 [ 0.36425158  0.88346729  0.59623871]]

sum of elements of the array is: 3.83368766086
the largest element in the array is: 0.979008267764

column-wise sum of elements of the array are: [ 1.34325985  1.19076519  1.29966262]
row-wise largest element of the array are: [ 0.97900827  0.88346729]


#### Universal Functions
 - 'ufunc' work on each element of the array and return an array as the output
 - sqrt, add, exp, mean, median, std, ceil, floor, corrcoef, cov, round, transpose, sort are few examples

#### Indexing - Slicing - Iterating

 -  1-D Array

In [195]:
a = arange(10) ** 3
print("the array \'a\' is: " + str(a))
# Python is a zero-based indexing language

# Indexing
print("\nINDEXING")

print("2nd element of the array is: " + str(a[2]))

# Using index, for value replacement
a[1] = 420
print("new elements of the array are: " + str(a))

# Slicing
# Also note that, index 5 is excluded from the slice
print("\nSLICING")
print("the slice of the array from index (2 to 4) is: " + str(a[2:5]))

# Using slice, to go from element 0 to 5 and replace every 2nd element until stop limit with 0
a[ : 6: 2] = 0
print("the new array with every 2nd element until index 5 replaced with -1000 is: " + str(a))

# Reversing an array
print("\nREVERSING the order of elements of an array")
a[ : : -1]

# Iterating through an array
print("\nITERATING")

for i in a:
    print("I am at element: " + str(i))

the array 'a' is: [  0   1   8  27  64 125 216 343 512 729]

INDEXING
2nd element of the array is: 8
new elements of the array are: [  0 420   8  27  64 125 216 343 512 729]

SLICING
the slice of the array from index (2 to 4) is: [ 8 27 64]
the new array with every 2nd element until index 5 replaced with -1000 is: [  0 420   0  27   0 125 216 343 512 729]

REVERSING the order of elements of an array

ITERATING
I am at element: 0
I am at element: 420
I am at element: 0
I am at element: 27
I am at element: 0
I am at element: 125
I am at element: 216
I am at element: 343
I am at element: 512
I am at element: 729


 - Multidimensional array

In [196]:
# Creating the multi-dimensional array
def f(x, y):
    return 10*x+y

b = fromfunction(f, (5, 4), dtype = int) # fromfunction is used to create an array by executing the function over each coordinate

print("Array \'b\' is: ")
b

Array 'b' is: 


array([[ 0,  1,  2,  3],
       [10, 11, 12, 13],
       [20, 21, 22, 23],
       [30, 31, 32, 33],
       [40, 41, 42, 43]])

In [197]:
# Indexing

print("INDEXING")
print("element in 3rd row (row index 2) and 4th column (column index is 3) is: " + str(b[2, 3]))

# Slicing
print("\nSLICING")
print("every element in 2nd column (column index is 1) is: " + str(b[ : , 1]))

print("every element in 2nd row (row index is 1) is: " + str(b[ 1 , : ]))

print("\nevery element in 2nd and 3rd row is: " + str(b[1:3, :]))

print("\nall columns in 1st row of array are: " + str(b[0, 0:5]))

INDEXING
element in 3rd row (row index 2) and 4th column (column index is 3) is: 23

SLICING
every element in 2nd column (column index is 1) is: [ 1 11 21 31 41]
every element in 2nd row (row index is 1) is: [10 11 12 13]

every element in 2nd and 3rd row is: [[10 11 12 13]
 [20 21 22 23]]

all columns in 1st row of array are: [0 1 2 3]


In [198]:
# Iterating
print("ITERATING")
for row in b:
    print row*2

ITERATING
[0 2 4 6]
[20 22 24 26]
[40 42 44 46]
[60 62 64 66]
[80 82 84 86]


#### Shape Manipulation

In [202]:
print b

print("the shape of array \'b\' is: " + str(b.shape))

# To flatten the array
b.ravel()

[[ 0  1  2  3 10]
 [11 12 13 20 21]
 [22 23 30 31 32]
 [33 40 41 42 43]]
the shape of array 'b' is: (4L, 5L)


array([ 0,  1,  2,  3, 10, 11, 12, 13, 20, 21, 22, 23, 30, 31, 32, 33, 40,
       41, 42, 43])

In [213]:
# To change shape of array
print("CHANGE ARRAY SHAPE")
b.shape = (5, 4)  # cannot change the number of elements that the array can have
print b

# To transpose the array
# turns 1st column to 1st row, 2nd column to 2nd row and so on
print("\nTRANSPOSE")
print b.transpose()

CHANGE ARRAY SHAPE
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]

TRANSPOSE
[[ 0 10 20 30 40]
 [ 1 11 21 31 41]
 [ 2 12 22 32 42]
 [ 3 13 23 33 43]]


 - Stacking Arrays (Vertical stack - adds rows, Horizontal stack - adds columns)

In [237]:
a = floor(10*random.random((2, 2)))
print a

b = floor(10*random.random((2, 2)))
print b

[[ 8.  2.]
 [ 3.  3.]]
[[ 1.  0.]
 [ 1.  1.]]


In [245]:
print ("using vstack to add b as rows to a: ")
print vstack((a, b))

print ("\nusing vstack to add b as columns to a: ")
print hstack((a, b))

using vstack to add b as rows to a: 
[[ 8.  2.]
 [ 3.  3.]
 [ 1.  0.]
 [ 1.  1.]]

using vstack to add b as columns to a: 
[[ 8.  2.  1.  0.]
 [ 3.  3.  1.  1.]]


In [246]:
column_stack((a, b))

array([[ 8.,  2.,  1.,  0.],
       [ 3.,  3.,  1.,  1.]])

In [247]:
row_stack((a, b))

array([[ 8.,  2.],
       [ 3.,  3.],
       [ 1.,  0.],
       [ 1.,  1.]])

 - Splitting one array into several smaller ones

In [252]:
a = floor(10*random.random((2,12)))
print("Array is:\n" + str(a))

# all positions below are zero-index based
print("\nHSPLIT - splits the initial array by columns")
b = hsplit(a, 3) # hsplit works by splitting the array by columns
print b

print("\nVSPLIT - splits the initial array")
c = vsplit(a, 2) # vsplit works by splitting the array by rows
print c

print("\nWe can also specify the columns after which we want the array to be split")
d = hsplit(a, (3, 4))
print d

Array is:
[[ 1.  1.  7.  3.  3.  0.  5.  8.  2.  6.  7.  4.]
 [ 1.  9.  7.  4.  6.  6.  7.  5.  9.  0.  5.  1.]]

HSPLIT - splits the initial array by columns
[array([[ 1.,  1.,  7.,  3.],
       [ 1.,  9.,  7.,  4.]]), array([[ 3.,  0.,  5.,  8.],
       [ 6.,  6.,  7.,  5.]]), array([[ 2.,  6.,  7.,  4.],
       [ 9.,  0.,  5.,  1.]])]

VSPLIT - splits the initial array
[array([[ 1.,  1.,  7.,  3.,  3.,  0.,  5.,  8.,  2.,  6.,  7.,  4.]]), array([[ 1.,  9.,  7.,  4.,  6.,  6.,  7.,  5.,  9.,  0.,  5.,  1.]])]

We can also specify the columns after which we want the array to be split
[array([[ 1.,  1.,  7.],
       [ 1.,  9.,  7.]]), array([[ 3.],
       [ 4.]]), array([[ 3.,  0.,  5.,  8.,  2.,  6.,  7.,  4.],
       [ 6.,  6.,  7.,  5.,  9.,  0.,  5.,  1.]])]


#### Copies and Views

 - Simple assignment statements DO NOT MAKE COPIES of arrays

In [263]:
a = arange(12)
print("a: " + str(a))

b = a # no copy is being created. b and a are just different names for the same array object in memory
print("b: " + str(a))

print("\nChecking whether \'a\' and \'b\' are the same thing: ")
print(b is a)

print("Any changes made to b will get refelected on a\n")
b.shape = (3, 4)
print("New shape of b: " + str(b.shape))
print("New shape of a: " + str(a.shape))

a: [ 0  1  2  3  4  5  6  7  8  9 10 11]
b: [ 0  1  2  3  4  5  6  7  8  9 10 11]

Checking whether 'a' and 'b' are the same thing: 
True
Any changes made to b will get refelected on a

New shape of b: (3L, 4L)
New shape of a: (3L, 4L)
